; https://wiki.zshell.dev/ecosystem/plugins/f-sy-h
; List all themes with: fast-theme -l
; Set theme with: fast-theme -t <myThemeFilePath> (note: copy full path and paste)
; Created with: fast-theme --copy-shipped-theme default
; 147 = violet (comment)
; 215 = orange
; 220 = gold
; 48 = green
; 213 = pink

[base]
default          = none
unknown-token    = red,bold
commandseparator = none
redirection      = 213
here-string-tri  = 213
here-string-text = 18
here-string-var  = 215
; here-string-var  = cyan,bg:18
exec-descriptor  = yellow,bold
comment          = 146
correct-subtle   = 12
incorrect-subtle = red
subtle-separator = 48
subtle-bg        = bg:18
secondary        = free
; recursive-base   =

[command-point]
reserved-word  = 213
subcommand     = 215
alias          = 48
suffix-alias   = 48
global-alias   = bg:blue
builtin        = 48
function       = 48
command        = 48
precommand     = 48
hashed-command = 48
single-sq-bracket = 48
double-sq-bracket = 48
double-paren   = 48

[paths]
path          = cyan
; path          = magenta
pathseparator =
path-to-dir   = cyan
; path-to-dir   = magenta
globbing      = blue,bold
globbing-ext  = 13

[brackets]
paired-bracket = bg:blue
bracket-level-1 = 220,bold
bracket-level-2 = 206,bold
bracket-level-3 = cyan,bold

[arguments]
single-hyphen-option   = 215
double-hyphen-option   = 215
back-quoted-argument   = 215
single-quoted-argument = 15
; single-quoted-argument = 210
double-quoted-argument = 15
; double-quoted-argument = 210
dollar-quoted-argument = 15
; dollar-quoted-argument = 210

[in-string]
; backslash in $'...'
back-dollar-quoted-argument           = 215
; backslash or $... in "..."
back-or-dollar-double-quoted-argument = 215

[other]
variable             = 215
assign               = 215
assign-array-bracket = 48
history-expansion    = blue,bold

[math]
mathvar = blue,bold
mathnum = 141
matherr = red

[for-loop]
forvar = none
fornum = 141
; operator
foroper = 213
; separator
forsep = none,bold

[case]
case-input       = 48
case-parentheses = yellow
case-condition   = bg:blue
