#-------------------------------------------------------------------------------
#                                     Prompt
#-------------------------------------------------------------------------------
format = """$all$fill$time$line_break$character"""
# Disables printing new line at the start of the prompt
add_newline = false
command_timeout = 3000
# format = """$all$line_break$character"""
# right_format = """$time"""

#-------------------------------------------------------------------------------
#                                   Character
#-------------------------------------------------------------------------------
# ❯  X ➜
[character]
# success_symbol = "[☁️]()"
success_symbol = "[☁️ ](bold #39FF14)"
# error_symbol = "[☁️ ](bold red) "
error_symbol = "[❌](bold red)"

#-------------------------------------------------------------------------------
#                               Command Duration
#-------------------------------------------------------------------------------
[cmd_duration]
min_time = 1_000                    # Show command duration over 10,000 milliseconds (= 10 sec)
format = "took [$duration]($style)"

#-------------------------------------------------------------------------------
#                                   Directory
#-------------------------------------------------------------------------------
[directory]
truncation_length = 100
truncate_to_repo = false

#-------------------------------------------------------------------------------
#                                     Package
#-------------------------------------------------------------------------------
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

#-------------------------------------------------------------------------------
#                                     Python
#-------------------------------------------------------------------------------
[python]
version_format = ""

#-------------------------------------------------------------------------------
#                                     Fill
#-------------------------------------------------------------------------------
[fill]
symbol = " "
style = " "

#-------------------------------------------------------------------------------
#                                     Time
#-------------------------------------------------------------------------------
[time]
disabled = false
format = '[$time]($style) '
time_format = "%-I:%M:%S%P - %d/%m"
style = "bold white"
# format = '[\[ $time \]]($style) '
# time_format = "[%d/%m/%y - %-I:%M:%S%P]"
